---
title: "Descriptives (graphic)"
output: html_document
date: "2024-10-08"
---
```{r packages, include = F}
require(tidyverse)
require(igraph)
require(shiny)
require(RSiena)
require(rmdformats)
require(prettydoc)
require(hrbrthemes)
require(tint)
require(tufte)
require(psych)
```
```{r setup, include=FALSE}
demographics_hannah.csv <- read_csv("demographics_hannah.csv")
```

```{r thingssss}

#create DF
#demographics_my_data <- df_soc[[1]]
#demographics_my_data <- as.data.frame(do.call(rbind, demographics_my_data))
#Naam <- subset_gender[,1]
#last_columns_gender <- subset_gender[,c(22:24)]
#usable_gender <- cbind(Naam, last_columns_gender)
#usable_gender <- usable_gender %>%
#  drop_na(born_in)
#usable_gender_2 <- left_join(demographics_my_data, usable_gender, by = "Naam")
#view(usable_gender_2)

#Make Binary Variables 
#usable_gender_2 <- usable_gender_2 %>%
#  mutate(
#    born_in_binary = ifelse(born_in == "Netherlands", 1, 0)
#  )
#usable_gender_2 <- usable_gender_2 %>%
#  mutate(
#    hoogleraar = ifelse(Functie.24 == "Hoogleraar", 1,0),
#  )
#usable_gender_2 <- usable_gender_2 %>%
#  mutate(
#    functie = as.factor(Functie.24)
#  ) 
#usable_gender_2 <- usable_gender_2 %>%
#  mutate(
#    functie = as.numeric(functie))
#view(usable_gender_2)
```


# Let's Get Some Info(graphics)
```{r}
demographics_hannah.csv %>%
  mutate(
    perc_female = ifelse(perc_female >= 0.5, 1, 0)
  ) %>%
  count(perc_female)
hist(demographics_hannah.csv$perc_female)
demographics_hannah.csv %>%
  count(born_in_binary)
hist(demographics_hannah.csv$born_in_binary)
demographics_hannah.csv %>%
  count(white_or_not)
hist(demographics_hannah.csv$white_or_not)
demographics_hannah.csv %>%
  count(Functie.22)
hist(demographics_hannah.csv$functie)
demographics_hannah.csv %>%
  count(hoogleraar)
hist(demographics_hannah.csv$hoogleraar)
```




